name: clean_network
description: A new Flutter project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.13.0 <3.0.0"
  flutter: ">=1.17.0"

# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  #NETWORK
  json_annotation: ^4.0.1
  json_serializable: ^4.1.0
  dio: ^4.0.0

  #UTITILES
  freezed_annotation: ^0.14.1
  freezed: ^0.14.1+1
  connectivity: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.12.2
  mobx_codegen: ^2.0.1+3

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
